### ISSUE TITLE
Gulp Default Task - Bumps `Error: module "@popperjs/core" not found`

### ISSUE THREAD

**Issue by app-generator** [app-generator/adminator-v2#2]
Tested with Node 14.0

Commands executed: 

```bash
npm i ; gulp 
```

Error log:

```log
[07:05:18] Using gulpfile D:\work\repo-kits\adminator-v2\gulpfile.js
[07:05:18] Starting 'default'...
[07:05:18] Starting 'serve'...
[07:05:18] Starting 'scss'...
[07:05:35] Finished 'scss' after 16 s
[07:05:35] Starting 'html'...
[07:05:36] Finished 'html' after 744 ms
[07:05:38] Starting 'build'...
[07:05:47] 'build' errored after 8.89 s
[07:05:47] Error: module "@popperjs/core" not found from "D:\\work\\repo-kits\\adminator-v2\\node_modules\\bootstrap\\dist\\js\\bootstrap.js"
    at notFound (D:\work\repo-kits\adminator-v2\node_modules\browserify\index.js:803:15)
    at D:\work\repo-kits\adminator-v2\node_modules\browserify\index.js:754:23
```

**Comment by app-generator** [comment]
Same thing with **Node 16**. Here are the commands: 

- clone the project (`fresh download`)
- check node version -> v16
- `npm install`
- `gulp` 

The error log:

```log
PS D:\work\repo-kits\adminator-v2> gulp
[07:53:49] Using gulpfile D:\work\repo-kits\adminator-v2\gulpfile.js
[07:53:49] Starting 'default'...
[07:53:49] Starting 'serve'...
[07:53:49] Starting 'scss'...
[07:54:00] Finished 'scss' after 11 s
[07:54:00] Starting 'html'...
[07:54:00] Finished 'html' after 124 ms
[07:54:00] Starting 'fonts'...
[07:54:01] Finished 'fonts' after 1.14 s
[07:54:01] Starting 'images'...
[07:54:02] Finished 'images' after 902 ms
[07:54:02] Starting 'build'...
[07:54:11] 'build' errored after 9 s
[07:54:11] Error: module "@popperjs/core" not found from "D:\\work\\repo-kits\\adminator-v2\\node_modules\\bootstrap\\dist\\js\\bootstrap.js"
    at notFound (D:\work\repo-kits\adminator-v2\node_modules\browserify\index.js:803:15)
    at D:\work\repo-kits\adminator-v2\node_modules\browserify\index.js:754:23
    at D:\work\repo-kits\adminator-v2\node_modules\browser-resolve\index.js:185:24
```

**Comment by 9sumit** [comment]
Build Error: Module "@popperjs/core" not found Solved.

**Comment by 9sumit** [comment]
Issue solved.

**Comment by app-generator** [comment]
Validated. Ty @9sumit
